spring:
    application:
        name: mcsv_auth
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: ${COGNITO_CLIENT_ID}
                        client-secret: ${COGNITO_CLIENT_SECRET}
                        scope: openid, profile, email
                provider:
                    cognito:
                        issuerUri: ${COGNITO_ISSUR_URI}
                        user-name-attribute: username

server:
    port: 8090

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${server.port}

