spring:
    application:
        name: mcsv_auth
    security:
        oauth2:
           resourceserver:
                jwt:
                    issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_bENNgzSp5
                    jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_bENNgzSp5/.well-known/jwks.json

server:
    port: 8090

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${server.port}

